name: flutter_llm_chat
description: A chat application using OpenAI API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.7.0
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  flutter_dotenv: ^5.2.1
  supabase_flutter: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
